"use client";

import { useState, useEffect, useCallback } from "react";
import {
  Search,
  Plus,
  Trash2,
  RefreshCw,
  Loader2,
  BookOpen,
  Tag,
  User as UserIcon,
  FileText,
  Lightbulb,
  Building,
} from "lucide-react";
import { useKnowledgeStore } from "@/stores/knowledge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import type { KnowledgeEntryCreateRequest, KnowledgeEntryType, RevisitLevel } from "@/types";

const ENTRY_TYPE_OPTIONS = [
  { value: "", label: "All Types" },
  { value: "episode_summary", label: "Episode Summaries" },
  { value: "topic", label: "Topics" },
  { value: "guest", label: "Guests" },
  { value: "key_fact", label: "Key Facts" },
  { value: "note", label: "Notes" },
  { value: "business_context", label: "Business Context" },
  { value: "source_material", label: "Source Material" },
];

const REVISIT_OPTIONS = [
  { value: "never", label: "Don't Repeat" },
  { value: "brief", label: "Brief Recap OK" },
  { value: "recurring", label: "Recurring Theme" },
];

const TYPE_ICONS: Record<string, typeof BookOpen> = {
  episode_summary: BookOpen,
  topic: Tag,
  guest: UserIcon,
  key_fact: Lightbulb,
  note: FileText,
  business_context: Building,
  source_material: FileText,
};

const REVISIT_BADGE_VARIANT: Record<string, "default" | "secondary" | "warning" | "success"> = {
  never: "default",
  brief: "warning",
  recurring: "success",
};

interface KnowledgeListProps {
  podcastId: string;
}

export function KnowledgeList({ podcastId }: KnowledgeListProps) {
  const {
    entries,
    isLoading,
    isSaving,
    error,
    selectedIds,
    loadEntries,
    createEntry,
    updateEntry,
    deleteEntry,
    bulkDelete,
    toggleSelected,
    selectAll,
    clearSelection,
  } = useKnowledgeStore();

  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [newEntry, setNewEntry] = useState<KnowledgeEntryCreateRequest>({
    entry_type: "business_context",
    title: "",
    content: "",
    revisit: "recurring",
  });

  const fetchEntries = useCallback(() => {
    loadEntries(podcastId, {
      search: search || undefined,
      entry_type: typeFilter || undefined,
    });
  }, [podcastId, search, typeFilter, loadEntries]);

  useEffect(() => {
    fetchEntries();
  }, [fetchEntries]);

  const handleSearch = (value: string) => {
    setSearch(value);
  };

  const handleCreate = async () => {
    if (!newEntry.title.trim()) return;
    await createEntry(podcastId, newEntry);
    setNewEntry({
      entry_type: "business_context",
      title: "",
      content: "",
      revisit: "recurring",
    });
    setShowForm(false);
  };

  const handleRevisitChange = async (entryId: string, revisit: RevisitLevel) => {
    await updateEntry(podcastId, entryId, { revisit });
  };

  const handleBulkDelete = async () => {
    const ids = Array.from(selectedIds);
    if (ids.length === 0) return;
    await bulkDelete(podcastId, ids);
  };

  const isAutoGenerated = (entry: (typeof entries)[0]) => !!entry.episode_id;

  return (
    <div className="space-y-4">
      {error && (
        <div className="rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 p-3">
          <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
        </div>
      )}

      {/* Search and filters */}
      <div className="flex items-center gap-3">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[hsl(var(--muted-foreground))]" />
          <input
            type="text"
            value={search}
            onChange={(e) => handleSearch(e.target.value)}
            placeholder="Search knowledge base..."
            className="w-full pl-9 pr-3 py-2 text-sm rounded-lg border border-[hsl(var(--border))] bg-[hsl(var(--background))] text-[hsl(var(--foreground))] focus:outline-none focus:ring-2 focus:ring-primary-500"
          />
        </div>
        <Select
          options={ENTRY_TYPE_OPTIONS}
          value={typeFilter}
          onChange={(value) => setTypeFilter(value)}
        />
        <Button variant="outline" size="sm" onClick={() => setShowForm(true)}>
          <Plus className="w-4 h-4" />
          Add Entry
        </Button>
      </div>

      {/* Bulk actions */}
      {selectedIds.size > 0 && (
        <div className="flex items-center gap-3 p-2 rounded-lg bg-[hsl(var(--muted))]">
          <span className="text-sm text-[hsl(var(--foreground))]">
            {selectedIds.size} selected
          </span>
          <Button
            variant="outline"
            size="sm"
            onClick={handleBulkDelete}
            className="text-red-600"
          >
            <Trash2 className="w-3 h-3" />
            Delete Selected
          </Button>
          <button
            onClick={clearSelection}
            className="text-sm text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]"
          >
            Clear
          </button>
          <button
            onClick={selectAll}
            className="text-sm text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]"
          >
            Select All
          </button>
        </div>
      )}

      {/* Entry list */}
      {isLoading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="w-6 h-6 animate-spin text-[hsl(var(--muted-foreground))]" />
        </div>
      ) : entries.length === 0 ? (
        <div className="text-center py-12">
          <BookOpen className="w-10 h-10 mx-auto mb-3 text-[hsl(var(--muted-foreground))]" />
          <p className="text-sm text-[hsl(var(--muted-foreground))]">
            No knowledge entries yet. Add business context or generate episode
            summaries.
          </p>
        </div>
      ) : (
        <div className="space-y-1">
          {entries.map((entry) => {
            const Icon = TYPE_ICONS[entry.entry_type] || FileText;
            const isSelected = selectedIds.has(entry.id);

            return (
              <div
                key={entry.id}
                className={`flex items-start gap-3 p-3 rounded-lg border transition-colors ${
                  isSelected
                    ? "border-primary-300 bg-primary-50/50 dark:border-primary-700 dark:bg-primary-950/20"
                    : "border-transparent hover:bg-[hsl(var(--muted))]"
                }`}
              >
                <input
                  type="checkbox"
                  checked={isSelected}
                  onChange={() => toggleSelected(entry.id)}
                  className="mt-1 rounded border-[hsl(var(--border))]"
                />
                <Icon className="w-4 h-4 mt-0.5 text-[hsl(var(--muted-foreground))] flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className="text-sm font-medium text-[hsl(var(--foreground))] truncate">
                      {entry.title}
                    </span>
                    <Badge
                      variant={REVISIT_BADGE_VARIANT[entry.revisit] || "default"}
                    >
                      {entry.revisit === "never"
                        ? "Don't Repeat"
                        : entry.revisit === "brief"
                          ? "Brief OK"
                          : "Recurring"}
                    </Badge>
                    {isAutoGenerated(entry) ? (
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400">
                        Auto
                      </span>
                    ) : (
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]">
                        Manual
                      </span>
                    )}
                  </div>
                  {entry.content && (
                    <p className="text-xs text-[hsl(var(--muted-foreground))] line-clamp-1">
                      {entry.content}
                    </p>
                  )}
                </div>
                <div className="flex items-center gap-1">
                  <select
                    value={entry.revisit}
                    onChange={(e) =>
                      handleRevisitChange(
                        entry.id,
                        e.target.value as RevisitLevel
                      )
                    }
                    className="text-xs rounded border border-[hsl(var(--border))] bg-[hsl(var(--background))] px-1.5 py-1"
                  >
                    {REVISIT_OPTIONS.map((opt) => (
                      <option key={opt.value} value={opt.value}>
                        {opt.label}
                      </option>
                    ))}
                  </select>
                  <button
                    onClick={() => deleteEntry(podcastId, entry.id)}
                    className="p-1 rounded hover:bg-red-50 dark:hover:bg-red-900/20 text-[hsl(var(--muted-foreground))] hover:text-red-600 transition-colors"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Add Entry Form */}
      {showForm && (
        <Card>
          <CardContent className="p-4 space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-semibold text-[hsl(var(--foreground))]">
                Add Knowledge Entry
              </h4>
              <button
                onClick={() => setShowForm(false)}
                className="text-sm text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--foreground))]"
              >
                Cancel
              </button>
            </div>

            <Select
              label="Type"
              options={ENTRY_TYPE_OPTIONS.filter((o) => o.value !== "")}
              value={newEntry.entry_type}
              onChange={(value) =>
                setNewEntry({
                  ...newEntry,
                  entry_type: value as KnowledgeEntryType,
                })
              }
            />

            <Input
              label="Title"
              value={newEntry.title}
              onChange={(e) =>
                setNewEntry({ ...newEntry, title: e.target.value })
              }
              placeholder="Brief bullet-point summary..."
            />

            <Textarea
              label="Details (optional)"
              value={newEntry.content || ""}
              onChange={(e) =>
                setNewEntry({ ...newEntry, content: e.target.value })
              }
              placeholder="Additional context, details, or source material..."
              rows={3}
            />

            <Select
              label="Revisit Level"
              options={REVISIT_OPTIONS}
              value={newEntry.revisit || "recurring"}
              onChange={(value) =>
                setNewEntry({ ...newEntry, revisit: value as RevisitLevel })
              }
            />

            <Button
              onClick={handleCreate}
              disabled={isSaving || !newEntry.title.trim()}
            >
              {isSaving ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Plus className="w-4 h-4" />
              )}
              Add Entry
            </Button>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
